trigger: none

stages:
- stage: RShinyAppDeploy
  jobs:
  - job: BuildContainer
    pool:
      vmImage: ubuntu-latest

    steps:
    - script: |
        docker build . --file Dockerfile --tag my-r-shiny-app:latest
        docker tag my-r-shiny-app:latest acrhuduatranslink.azurecr.io/my-r-shiny-app:latest
        az login --service-principal -u $(APPID) -p $(SECRET) --tenant $(TENANTID)
        az acr login -n acrhuduatranslink
        docker push acrhuduatranslink.azurecr.io/my-r-shiny-app:latest
      displayName: 'Build the Docker image and Push to ACR'
  - job: DeployApp
    dependsOn: BuildContainer
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        az login --service-principal -u $(APPID) -p $(SECRET) --tenant $(TENANTID)
        az webapp config set --resource-group phac --name phachuduarshinyapp --linux-fx-version "DOCKER|acrhuduatranslink.azurecr.io/my-r-shiny-app:latest"          
        az webapp restart --name phachuduarshinyapp --resource-group phac
      displayName: 'Run app in App Service from ACR'