name: Docker Image CI

on:
   push:
    branches: [ main ]

jobs:

  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and Push to ACR test
      run: |
        docker build . --file Dockerfile --tag my-r-shiny-app:latest
        docker tag my-r-shiny-app:latest azuremlhuduaa31f772f.azurecr.io/my-r-shiny-app:latest
        az login --service-principal -u ${{ secrets.APPID }} -p ${{ secrets.SECRET }} --tenant ${{ secrets.TENANTID }}
        az acr login -n azuremlhuduaa31f772f
        docker push azuremlhuduaa31f772f.azurecr.io/my-r-shiny-app:latest
  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run app in APp Service from ACR test
      run: |
        az login --service-principal -u ${{ secrets.APPID }} -p ${{ secrets.SECRET }} --tenant ${{ secrets.TENANTID }}
        az webapp config set --resource-group r-shiny-app --name r-shiny-app-hudua-cd --linux-fx-version "DOCKER|azuremlhuduaa31f772f.azurecr.io/my-r-shiny-app:latest"          
        az webapp restart --name r-shiny-app-hudua-cd --resource-group r-shiny-app
